<template>
  <v-select v-model="razaSelect" :items="razaItems" label="Raza"></v-select>
</template>

<script>
export default {
  data() {
    return {
      razaItems: ['uno', 'dos'],
      razaPerros: [
        "Affenpinscher",
        "Afgano",
        "Akita japonés",
        "Basenji",
        "Basset Azul De Gascuña",
        "Basset Hound",
        "Basset leonado de Bretaña",
        "Beagle",
        "Beauceron",
        "Bedlington Terrier",
        "Bergamasco",
        "Bichón boloñés",
        "Bichón Frisé",
        "Bloodhound",
        "Bobtail o Antiguo Pastor Inglés",
        "Border Collie",
        "Border Terrier",
        "Borzoi",
        "Boston Terrier",
        "Bóxer",
        "Boyero de Berna",
        "Boyero de Flandes",
        "Bracco italiano",
        "Braco alemán de pelo corto",
        "Braco alemán de pelo duro",
        "Braco de Weimar (de pelo corto/suave)",
        "Braco húngaro",
        "Braco húngaro de pelo duro",
        "Bretón",
        "Buhund Noruego",
        "Bull Terrier",
        "Bull Terrier Miniatura",
        "Bulldog",
        "Bulldog francés",
        "Bullmastiff",
        "Cairn terrier",
        "Caniche Enano",
        "Caniche Grande",
        "Caniche Toy",
        "Carlino",
        "Cavalier King Charles Spaniel",
        "Cazador de Alces Noruego (Elkhound Noruego)",
        "Chihuahua (de pelo largo)",
        "Chihuahua (de pelo suave)",
        "Chin japonés",
        "Chow Chow (de pelo duro)",
        "Chow Chow (de pelo suave)",
        "Clumber Spaniel",
        "Cobrador de Nueva Escocia",
        "Cocker Spaniel Americano",
        "Cocker spaniel inglés",
        "Collie barbudo",
        "Collie de Pelo Corto",
        "Corgi Galés (de Cardigan) (Pelaje medio/largo).",
        "Corgi Galés de Pembroke",
        "Cotón de Tulear",
        "Crestado Chino",
        "Dachshund (pelo largo)",
        "Dálmata",
        "Dandie Dinmont Terrier",
        "Dóbermann",
        "Dogo de Burdeos",
        "Esquimal Canadiense",
        "Field spaniel",
        "Fox terrier de pelo duro",
        "Fox terrier de pelo liso",
        "Foxhound",
        "Galgo",
        "Galgo italiano",
        "Golden Retriever",
        "Gran azul de Gascuña",
        "Gran danés",
        "Grifón belga (pelaje corto y suave)",
        "Grifón de Bruselas (pelaje corto y áspero)",
        "Grifón vandeano basset (grande)",
        "Grifón vandeano basset (pequeño)",
        "Habanero",
        "Hamilton stovare",
        "Hovawart",
        "Husky Siberiano",
        "Keeshond",
        "Kerry blue terrier",
        "King Charles Spaniel",
        "Komondor",
        "Kuvasz húngaro",
        "Labrador Retriever",
        "Laekenois",
        "Lakeland Terrier",
        "Lancashire Heeler",
        "Lebrel escocés",
        "Leonberger",
        "Lhasa apso",
        "Lobero irlandés",
        "Lowchen (pequeño perro león)",
        "Malamute de Alaska",
        "Malinois",
        "Maltés",
        "Manchester terrier",
        "Mastín Inglés o Mastiff",
        "Mastín Napolitano",
        "Mastín Tibetano",
        "Munsterlander (Grande)",
        "Norfolk Terrier (Terrier de Norfolk)",
        "Otterhound",
        "Papillón",
        "Parson Jack Russell Terrier (de pelaje corto/suave)",
        "Pastor australiano",
        "Pastor belga Groenendael",
        "Pastor belga Laekenois",
        "Pastor belga Malinois",
        "Pastor belga Tervueren",
        "Pastor de Anatolia",
        "Pastor de Brie o Briard",
        "Pastor de los Pirineos",
        "Pastor de Maremma",
        "Pastor de Shetland o Shetland Sheepdog",
        "Pastor ganadero australiano",
        "Pastor Lapón de Suecia",
        "Pastor Polaco de las Llanuras",
        "Perro de Agua Español",
        "Perro de agua irlandés",
        "Perro de Agua Portugués",
        "Perro de Canaán",
        "Perro de Montaña de los Pirineos",
        "Perro del Faraón",
        "Perro finlandés de Laponia",
        "Perro pastor alemán",
        "Perro salchicha (Miniatura de pelo duro)",
        "Perro salchicha (Miniatura de pelo largo)",
        "Perro salchicha (Miniatura de pelo liso)",
        "Perro salchicha (pelo duro)",
        "Perro salchicha (pelo liso)",
        "Perro Serra da Estrela",
        "Pinscher (Alemán)",
        "Pinscher Miniatura",
        "Podenco ibicenco (pelaje corto y liso)",
        "Pointer",
        "Pomerania",
        "Puli húngaro",
        "Retriever de Chesapeake",
        "Retriever de pelo liso",
        "Retriever de pelo rizado",
        "Rhodesian Ridgeback o Crestado Rodesiano",
        "Rottweiler",
        "Rough Collie o Pastor Escocés de Pelo Largo",
        "Sabueso bávaro de montaña",
        "Sabueso Italiano (de pelo corto/suave)",
        "Saluki o Galgo Persa",
        "Samoyedo",
        "San Bernardo (pelaje medio/largo)",
        "Schipperke",
        "Schnauzer Estándar",
        "Schnauzer gigante",
        "Schnauzer Miniatura",
        "Scottish Terrier o Terrier Escocés",
        "Sealyham Terrier",
        "Setter escocés",
        "Setter inglés",
        "Setter irlandés",
        "Setter irlandés rojo y blanco",
        "Shar Pei",
        "Shiba inu japonés",
        "Shih Tzu",
        "Skye Terrier",
        "Sloughi o Galgo Árabe",
        "Soft Coated Wheaten Terrier",
        "Spaniel holandés",
        "Spaniel Tibetano",
        "Spinone italiano",
        "Spitz alemán mediano",
        "Spitz alemán pequeño",
        "Spitz finlandés",
        "Spitz japonés",
        "Springer Spaniel Galés",
        "Springer spaniel inglés",
        "Staffordshire Bull Terrier",
        "Sussex Spaniel",
        "Terranova (Newfoundland)",
        "Terrier australiano",
        "Terrier Checo",
        "Terrier de Airedale",
        "Terrier de Norwich (Norwich Terrier)",
        "Terrier Galés",
        "Terrier irlandés",
        "Terrier sedoso australiano",
        "Terrier Tibetano",
        "Toy terrier inglés (Negro y fuego)",
        "Vallhund Sueco",
        "West Highland White Terrier",
        "Whippet",
        "Xoloitzcuintle (Mediano)",
        "Yorkshire Terrier"
      ],
      razaGatos: [
        "Oriental de pelo largo",
        "Selkirk rex",
        "Abisinio",
        "Americano de pelo duro",
        "Asiático",
        "Azul ruso",
        "Balinés",
        "Bengalí",
        "Birmano",
        "Bobtail japonés de pelo corto",
        "Bobtail japonés de pelo largo",
        "Bombay",
        "Bosque de Noruega",
        "Bosque de Siberia",
        "Británico de pelo corto",
        "Burmés",
        "Burmilla",
        "Chinchilla",
        "Cornish rex",
        "Cymric",
        "Devon rex",
        "Exótico de pelo corto",
        "Fold escocés",
        "Khao Manee",
        "Korat",
        "Laperm",
        "Maine coon",
        "Manx",
        "Mau egipcio",
        "Mist australiano",
        "Munchkin",
        "Ocigato",
        "Oriental de pelo corto",
        "Persa de pelo largo",
        "Pixie bob",
        "Ragdoll",
        "Savannah",
        "Siamés",
        "Singapura",
        "Snowshoe",
        "Somali",
        "Sphynx",
        "Tiffanie",
        "Tonkinese",
        "Van turco"
      ]
    };
  },
  create() {
    if (this.input == "gato") this.razaItems = this.razaGatos;
      else this.razaItems = this.razaPerros;
  },
  props: {
    input: String,
    razaSelect: String
  }
};
</script>


